# Generated by Django 5.2.8 on 2026-01-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cinema", "0001_initial"),
        ("movie", "0001_initial"),
        ("slot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bookingseat",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="slot.booking",
            ),
        ),
        migrations.AddField(
            model_name="bookingseat",
            name="cinema_seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinema.cinemaseat"
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="cinema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinema.cinema"
            ),
        ),
        migrations.AddField(
            model_name="slot",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="slot.slot"
            ),
        ),
    ]
